# build docs using sphinx and deploy to branch gh-pages
name: Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and commit documentation
      uses: sphinx-notes/pages@2.0
      with:
        documentation_path: doc
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
